services:
  - type: web
    name: engineering-platform
    runtime: docker
    plan: free
    region: virginia
    dockerfilePath: ./Dockerfile
    healthCheckPath: /

    envVars:
      - key: SPRING_DATABASE_HOST
        fromDatabase:
          name: engineering-platform-db
          property: host

      - key: SPRING_DATABASE_NAME
        fromDatabase:
          name: engineering-platform-db
          property: database

      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: engineering-platform-db
          property: user

      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: engineering-platform-db
          property: password

databases:
  - name: engineering-platform-db
    plan: free
    region: virginia