spring.application.name=engineering-platform

# Server
server.port=${PORT:8080}

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${SPRING_DATABASE_HOST}:5432/${SPRING_DATABASE_NAME}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Twelvedata API
twelvedata.api.key=${TWELVEDATA_API_KEY}