spring.application.name=engineering-platform

# Server
server.port=${PORT:8080}

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/engineering_platform
spring.datasource.username=postgres
spring.datasour
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=truece.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.properties.hibernate.format_sql=true